我们可以通过使用  try..except  来处理异常状况。一般来说我们会把通常的语句放在 try 代
码块中，将我们的错误处理器代码放置在 except 代码块中。
```python
try:
    text = input('Enter something -->')
except EOFError:
    print('Why did you do an EOF on me ?')
except KeyboardInterrupt:
    print('You cancelled the operation.')
else:
    print('You entered {}'.format(text))

```
- 抛出异常
你可以通过  raise  语句来引发一次异常，具体方法是提供错误名或异常名以及要抛出
（Thrown）异常的对象。你能够引发的错误或异常必须是直接或间接从属于  Exception  （异常） 类的派生类。
```python
# encoding=UTF-8

class ShortInputException(Exception):
    def __init__(self, length, atleast):
        Exception.__init__(self)
        self.length = length
        self.atleast = atleast

try:
    text = input('Enter something -->')
    if len(text) < 3:
        raise ShortInputException(len(text), 3)
except EOFError:
    print('Why did you do an EOF on me？')
except ShortInputException as ex:
    print(('ShortInputException: The input was ' + '{0} long,expected at least {1}').format(ex.length, ex.atleast))
else:
    print('No exception was raise.')

```
输出：
```python
D:\Python\python.exe C:/Users/fdd/PycharmProjects/helloworld/exceptions_raise.py
Enter something -->a
ShortInputException: The input was 1 long,expected at least 3

Process finished with exit code 0

```
在  except  子句中，我们提及了错误类，将该类存储  as（为）  相应的错误名或异常名。这类似于函数调用中的形参与实参。在这个特殊的  except  子句中我们使用异常对象的  length与  atlease  字段来向用户打印一条合适的信息。
- try finally
```python
import sys
import time

f = None
try:
    f = open('poem.txt')
    while True:
        line = f.readline()
        if len(line) == 0:
            break
        print(line, end='')
        sys.stdout.flush()
        print("Press ctrl+c now")
        time.sleep(2)
except IOError:
    print("Could not find file poem.txt")
except IOError:
    print("!! You cancelled the reading form the file.")
finally:
    if f:
        f.close()
    print("(Cleaning up: Closed the file)")

```
- with 语句
在  try  块中获取资源，然后在  finally  块中释放资源是一种常见的模式。因此，还有一个with  语句使得这一过程可以以一种干净的姿态得以完成。